/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

/*
 * Stack Memory Calculations
 */

#define SIZE_TASK_STACK      1024U
#define SIZE_SCHED_STACK     1024U

#define SRAM_START           0x20000000U
#define SIZE_SRAM            ( (128) * (1024) )
#define SRAM_END             ( (SRAM_START) + (SIZE_SRAM) )

#define T1_STACK_START       SRAM_END
#define T2_STACK_START		 ( (SRAM_END) - (SIZE_TASK_STACK) )
#define T3_STACK_START		 ( (SRAM_END) - (2 * SIZE_TASK_STACK) )
#define T4_STACK_START		 ( (SRAM_END) - (3 * SIZE_TASK_STACK) )
#define SCHED_STACK_START    ( (SRAM_END) - (4 * SIZE_TASK_STACK) )

#define TICK_HZ 			 1000U

#define HSI_CLOCK 			 16000000U
#define SYSTICK_TIM_CLK		 HSI_CLOCK

/*
 * Tasks
 */

void task1_handler(); //Task 1
void task2_handler(); //Task 2
void task3_handler(); //Task 3
void task4_handler(); //Task 4

void init_systick_timer(uint32_t tick_hz);
__attribute__((naked)) void init_scheduler_stack(uint32_t sched_top_of_stack);

int main(void)
{
	init_scheduler_stack(SCHED_STACK_START);

	init_systick_timer(TICK_HZ);

    /* Loop forever */
	for(;;);
}


void task1_handler() {
	while(1) {
		printf("This is task 1\n");
	}
}

void task2_handler() {
	while(1) {
		printf("This is task 2\n");
	}
}

void task3_handler() {
	while(1) {
		printf("This is task 3\n");
	}
}

void task4_handler() {
	while(1) {
		printf("This is task 4\n");
	}
}

void init_systick_timer(uint32_t tick_hz) {
	uint32_t* pSRVR = (uint32_t*)  0xE000E014; //SysTick Reload Value Register
	uint32_t* pSCSR = (uint32_t*)  0xE000E010; //SysTick Control and Status Register
	uint32_t countVal = (SYSTICK_TIM_CLK / tick_hz) - 1; //Reload Value should be N-1 (Number of clock cycles - 1).

	//Clear value of SVR
	*pSRVR &= ~(0x00FFFFFFFF);

	//load value into SVR
	*pSRVR |= countVal;

	//Edit Settings
	*pSCSR |= (1 << 1); //Enables SysTick Exception Request
	*pSCSR |= (1 << 2); //Indicates that the clock source is the processor internal clock

	//Enable systick
	*pSCSR |= (1 << 0); //Enables the SysTick counter
}

/*
 * Must be a naked function to access MSP which is a special register
 */
__attribute__((naked)) void init_scheduler_stack(uint32_t sched_top_of_stack) {
	__asm volatile("MSR MSP, %0": : "r" (sched_top_of_stack) : ); //Puts value of the top of the stack into MSP
	__asm volatile("BX LR"); //Return from function call
}

void SysTick_Handler() {
	printf("In SysTick Handler\n");
}
