/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "main.h"

/*
 * Tasks to schedule
 */

void task1_handler(); //Task 1
void task2_handler(); //Task 2
void task3_handler(); //Task 3
void task4_handler(); //Task 4


/*
 * Function Declarations
 */
void init_systick_timer(uint32_t tick_hz);
__attribute__((naked)) void init_scheduler_stack(uint32_t sched_top_of_stack);
void init_tasks_stack();

/*
 * Global Variables
 */
uint32_t psp_of_tasks[MAX_TASKS];

int main(void)
{
	init_scheduler_stack(SCHED_STACK_START);

	init_tasks_stack();

	init_systick_timer(TICK_HZ);

    /* Loop forever */
	for(;;);
}


void task1_handler() {
	while(1) {
		printf("This is task 1\n");
	}
}

void task2_handler() {
	while(1) {
		printf("This is task 2\n");
	}
}

void task3_handler() {
	while(1) {
		printf("This is task 3\n");
	}
}

void task4_handler() {
	while(1) {
		printf("This is task 4\n");
	}
}

void init_systick_timer(uint32_t tick_hz) {
	uint32_t* pSRVR = (uint32_t*)  0xE000E014; //SysTick Reload Value Register
	uint32_t* pSCSR = (uint32_t*)  0xE000E010; //SysTick Control and Status Register
	uint32_t countVal = (SYSTICK_TIM_CLK / tick_hz) - 1; //Reload Value should be N-1 (Number of clock cycles - 1).

	//Clear value of SVR
	*pSRVR &= ~(0x00FFFFFFFF);

	//load value into SVR
	*pSRVR |= countVal;

	//Edit Settings
	*pSCSR |= (1 << 1); //Enables SysTick Exception Request
	*pSCSR |= (1 << 2); //Indicates that the clock source is the processor internal clock

	//Enable systick
	*pSCSR |= (1 << 0); //Enables the SysTick counter
}

/*
 * Must be a naked function to access MSP which is a special register
 */
__attribute__((naked)) void init_scheduler_stack(uint32_t sched_top_of_stack) {
	__asm volatile("MSR MSP, %0": : "r" (sched_top_of_stack) : ); //Puts value of the top of the stack into MSP
	__asm volatile("BX LR"); //Return from function call
}


void init_tasks_stack() {

}

void SysTick_Handler() {
	printf("In SysTick Handler\n");
}
